apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: web-route
  namespace: demo
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: default
spec:
  rules:
    - host: demo.mgmworkshop.com
      http:
        paths:
          - path: /
            backend:
              serviceName: web-service
              servicePort: 80
