apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/name: order-service
  name: order-service
  namespace: demo # TODO: change namespace
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: web
  selector:
    app: order-application
