apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/name: rabbit-mq
  name: rabbit-mq
  namespace: lhtran
spec:
  ports:
    - port: 5672
      targetPort: 5672
      name: web
    - port: 15672
      targetPort: 15672
      name: management
  selector:
    app: rabbit-mq
