apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-mq
  namespace: demo
  labels: &labels
    app: rabbit-mq
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: 1
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      containers:
        - image: rabbitmq:3-management
          name: rabbit-mq
          imagePullPolicy: Always
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: user
            - name: RABBITMQ_DEFAULT_PASS
              value: secret
          volumeMounts:
            - mountPath: /var/lib/rabbitmq
              name: rabbit-home-dir
          ports:
            - containerPort: 5672
            - containerPort: 15672
      volumes:
        - name: rabbit-home-dir
          emptyDir: {}
