apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-application
  namespace: demo # TODO: change namespace
  labels: &labels
    app: web-application
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: 1
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      containers:
        - image: lamth2/web-application:v1.1
          name: web-application
          args:
            - --spring.profiles.active=k8s
          env:
            - name: RABBIT_HOST
              value: 0.0.0.0 # TODO: correct rabbit ip pod
            - name: RABBIT_PORT
              value: "1234" # TODO: correct rabbit port
            - name: RABBIT_USERNAME
              value: username # TODO: correct rabbit username
            - name: RABBIT_PASSWORD
              value: passwrod # TODO: correct rabbit password
            - name: ORDER_SERVICE_HOST
              value: 0.0.0.0 # TODO: correct order service ip pod
          ports:
            - containerPort: 8080
